server:
  port: 8082
spring:
  application:
    name: cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1 # 强制在 Nacos 中注册为本地回环 IP，确保 Consumer 绝对能连上
    loadbalancer:
      cache:
        enabled: false